name: road_helperr
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  pin_code_fields: ^8.0.1
  video_player: ^2.7.2
  google_fonts: ^6.2.1
  gradient_slide_to_act: ^0.0.2
  shared_preferences: ^2.0.6
  image_picker: ^0.8.4+3
  geolocator: ^10.0.0 # تحديث
  geocoding: ^2.1.0 # تحديث
  google_maps_flutter: ^2.1.1 # تحديث
  url_launcher: ^6.1.5
  http: ^1.3.0
  connectivity_plus: ^5.0.2
  permission_handler: ^11.0.0 # تحديث
  location: ^5.0.0 # تحديث
  flutter_polyline_points: ^2.0.0 # تحديث

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/
    - assets/videos/1.mp4
    - assets/videos/2.mp4
    - assets/videos/3.mp4
